DROP TABLE category IF EXISTS;
DROP TABLE feed_item IF EXISTS;
DROP TABLE torrents IF EXISTS;
DROP TABLE tracker_role IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;

CREATE TABLE category (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category VARCHAR(255) NOT NULL,
  image    VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE feed_item (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
  content   CLOB,
  post_date TIMESTAMP,
  title     VARCHAR(255) NOT NULL,
  user_id   BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE torrents (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  checked     BOOLEAN,
  description CLOB,
  downloaded  INTEGER,
  info_hash   VARCHAR(255),
  leechers    INTEGER,
  name        VARCHAR(255) NOT NULL,
  seeders     INTEGER,
  size        BIGINT,
  uploaded    TIMESTAMP,
  category_id BIGINT,
  uploader    BIGINT       NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE tracker_role (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  role VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL
);

CREATE TABLE users (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  downloaded BIGINT,
  email      VARCHAR(255),
  lastlogin  TIMESTAMP,
  password   VARCHAR(255),
  points     INTEGER,
  registred  TIMESTAMP,
  title      VARCHAR(255),
  uploaded   BIGINT,
  username   VARCHAR(255),
  PRIMARY KEY (id)
);

ALTER TABLE category
  ADD CONSTRAINT UKoo4xayr0g0mkbajn7n2m3918u UNIQUE (category);
ALTER TABLE feed_item
  ADD CONSTRAINT FK6oiokgmyasslnv6eewpq93x7e FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE torrents
  ADD CONSTRAINT FKebw5stl6i06g5j03ru1m34na6 FOREIGN KEY (category_id) REFERENCES category;
ALTER TABLE torrents
  ADD CONSTRAINT FK2agf2asy1e9wly94383j2aqgu FOREIGN KEY (uploader) REFERENCES users;
